
-- EXERC 1

USE RA2023292261;


CREATE TABLE PACIENTES (
    COD_PACIENTE INT IDENTITY(1,1) PRIMARY KEY,
    NOME VARCHAR(200),
    IDADE INT
);


INSERT INTO PACIENTES (NOME, IDADE) VALUES
    ('THAIS', 35),
    ('FATIMA', 55),
    ('THEO', 15),
    ('MARCOS', 25),
    ('PEDRO', 29),
    ('HELLEN', 19);


CREATE TABLE CONSULTAS (
    CODIGO INT IDENTITY(1,1) PRIMARY KEY,
    DATA VARCHAR(20),
    DESCRICAO VARCHAR(200),
    COD_PACIENTE INT,
    CONSTRAINT FK_PACI FOREIGN KEY (COD_PACIENTE)
        REFERENCES PACIENTES(COD_PACIENTE)
);


INSERT INTO CONSULTAS (DATA, DESCRICAO, COD_PACIENTE) VALUES
    ('01/01/2024 12:00:00', 'DOR DE CABEÇA. ANADOR', 1),
    ('02/01/2024 15:00:00', 'RECONSULTA', 1),
    ('10/02/2024 17:00:00', 'PRESSÃO ALTA', 2),
    ('20/02/2024 13:00:00', 'ARRITMIA', 5),
    ('25/02/2024 18:00:00', 'RECONSULTA', 5),
    ('18/04/2024 08:00:00', 'COLUNA', 4);


-- EXERC 2

CREATE FUNCTION NumConsultas (@codigoPaciente INT)
RETURNS INT
AS
BEGIN
    DECLARE @total INT;

    SELECT @total = COUNT(COD_PACIENTE)
    FROM CONSULTAS
    WHERE COD_PACIENTE = @codigoPaciente;

    RETURN @total;
END;


SELECT dbo.NumConsultas(4)

-- EXERC 3

SELECT 
    COD_PACIENTE,
    NOME,
    IDADE,
    dbo.NumConsultas(COD_PACIENTE) AS TOTAL_CONSULTAS
FROM 
    PACIENTES;

-- EXERC 4
CREATE PROCEDURE Idademudada
AS
BEGIN
    UPDATE PACIENTES
    SET IDADE = IDADE + 1;
END;

SELECT * FROM PACIENTES 

EXEC Idademudada
